### ISSUE TITLE
project fails to deploy to vercel with new strapi version

### ISSUE THREAD

**Issue by troias** [remi2j/strapi-starter-next-corporate#66]

**Comment by troias** [comment]
on fresh install when loading to vercel. 

<html>
<body>


> Build error occurred
--
16:22:09.693 | Error: An error occured please try again
16:22:09.694 | at fetchAPI (/vercel/path0/.next/server/chunks/23.js:51:11)
16:22:09.694 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
16:22:09.694 | at async /vercel/path0/.next/server/pages/[[...slug]].js:1440:25
16:22:09.694 | at async /vercel/path0/.next/server/pages/[[...slug]].js:1439:26
16:22:09.694 | at async getStaticPaths (/vercel/path0/.next/server/pages/[[...slug]].js:1438:17)
16:22:09.694 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:16:80)
16:22:09.694 | at async /vercel/path0/node_modules/next/dist/build/utils.js:26:622
16:22:09.694 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:6:584) {


</body>
</html>

**Comment by troias** [comment]
My error. Had a trailing / in the env var url on vercel
